[features]
seeds = false
skip-lint = false
[programs.localnet]
adoptcontract = "DruXG4fVzPmdsfMqjNyrUaBv5aTvLnP9G43jemUcX1J1"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/elijah/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

## Necessary for test validator
[test.validator]
url = "https://api.devnet.solana.com"

# Token Metadata program
[[test.validator.clone]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"

# Token Program
[[test.validator.clone]]
address = "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"