[features]
seeds = false
skip-lint = false
[programs.localnet]
adoptcontract = "AAD24i9vjjW2RdrZvDpJptCfwfSPUQJtnKJ3kjjF8Kc8"

[programs.devnet]
adoptcontract = "AAD24i9vjjW2RdrZvDpJptCfwfSPUQJtnKJ3kjjF8Kc8"

[programs.mainnet]
adoptcontract = "AAD24i9vjjW2RdrZvDpJptCfwfSPUQJtnKJ3kjjF8Kc8"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "mainnet"
wallet = "/Users/elijah/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/adoptcontract.ts"
# anchor run create-vault
create-vault = "ts-node tests/initvault.ts" 
mint-to-pda = "ts-node tests/mintToPda.ts"
transfer-tickets = "ts-node tests/transferTicketsToPda"

## Necessary for test validator
[test.validator]
url = "https://api.devnet.solana.com"

# Token Metadata program
[[test.validator.clone]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"

# Token Program
[[test.validator.clone]]
address = "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"