[features]
seeds = false
skip-lint = false
[programs.localnet]
adoptcontract = "GntfZtKwsEZyygp35RM5ooBuHirNBCEdcnGSGByAgEtF"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/alsjourney/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
